# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/millionscard/pods-repo'
target 'AccountUpdaterDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PasswordChangerSDK', '0.1.4'

  # Pods for AccountUpdaterDemo

end
